/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as GlobalDesksRouteImport } from './routes/global-desks'
import { Route as DisclosuresRouteImport } from './routes/disclosures'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SymbolSlugRouteImport } from './routes/symbol.$slug'
import { Route as PortalTradeWorkspaceRouteImport } from './routes/portal.trade-workspace'
import { Route as PortalResetPasswordRouteImport } from './routes/portal.reset-password'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalInvestorRouteImport } from './routes/portal.investor'
import { Route as PortalAdminRouteImport } from './routes/portal.admin'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as PortalInvestorIndexRouteImport } from './routes/portal.investor.index'
import { Route as PortalAdminIndexRouteImport } from './routes/portal.admin.index'
import { Route as PortalSignupInvestorRouteImport } from './routes/portal.signup_.investor'
import { Route as PortalLoginInvestorRouteImport } from './routes/portal.login_.investor'
import { Route as PortalLoginAdminRouteImport } from './routes/portal.login_.admin'
import { Route as PortalInvestorWalletRouteImport } from './routes/portal.investor.wallet'
import { Route as PortalInvestorTransactionsRouteImport } from './routes/portal.investor.transactions'
import { Route as PortalInvestorTradeHistoryRouteImport } from './routes/portal.investor.trade-history'
import { Route as PortalInvestorTradeRouteImport } from './routes/portal.investor.trade'
import { Route as PortalInvestorSupportRouteImport } from './routes/portal.investor.support'
import { Route as PortalInvestorSettingsRouteImport } from './routes/portal.investor.settings'
import { Route as PortalInvestorProfileRouteImport } from './routes/portal.investor.profile'
import { Route as PortalInvestorPortfolioRouteImport } from './routes/portal.investor.portfolio'
import { Route as PortalInvestorPerformanceRouteImport } from './routes/portal.investor.performance'
import { Route as PortalInvestorOnboardingRouteImport } from './routes/portal.investor.onboarding'
import { Route as PortalInvestorKycRouteImport } from './routes/portal.investor.kyc'
import { Route as PortalInvestorApplyRouteImport } from './routes/portal.investor.apply'
import { Route as PortalAdminTradeHistoryRouteImport } from './routes/portal.admin.trade-history'
import { Route as PortalAdminStrategiesRouteImport } from './routes/portal.admin.strategies'
import { Route as PortalAdminRiskRouteImport } from './routes/portal.admin.risk'
import { Route as PortalAdminOnboardingRouteImport } from './routes/portal.admin.onboarding'
import { Route as PortalAdminGlobalDeskRouteImport } from './routes/portal.admin.global-desk'
import { Route as PortalAdminFundingRouteImport } from './routes/portal.admin.funding'
import { Route as PortalAdminClientsRouteImport } from './routes/portal.admin.clients'
import { Route as PortalAdminAuditRouteImport } from './routes/portal.admin.audit'
import { Route as PortalAdminAdminsRouteImport } from './routes/portal.admin.admins'
import { Route as ApiPublicTickerQuotesRouteImport } from './routes/api/public/ticker-quotes'
import { Route as ApiPublicSymbolDetailRouteImport } from './routes/api/public/symbol-detail'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicSchemaReadinessRouteImport } from './routes/api/public/schema-readiness'
import { Route as ApiPublicResolveLoginEmailRouteImport } from './routes/api/public/resolve-login-email'
import { Route as ApiPublicPaypalWebhookRouteImport } from './routes/api/public/paypal-webhook'
import { Route as ApiPublicLiveMarketQuotesRouteImport } from './routes/api/public/live-market-quotes'
import { Route as ApiPublicLiveMarketNewsRouteImport } from './routes/api/public/live-market-news'
import { Route as ApiPublicAuthHealthRouteImport } from './routes/api/public/auth-health'
import { Route as ApiPublicAssetListingQuotesRouteImport } from './routes/api/public/asset-listing-quotes'
import { Route as ApiPublicAdminSignupRouteImport } from './routes/api/public/admin-signup'
import { Route as ApiPortalWalletActionsRouteImport } from './routes/api/portal/wallet-actions'
import { Route as ApiPortalTradeHistoryRouteImport } from './routes/api/portal/trade-history'
import { Route as ApiPortalTicketsRouteImport } from './routes/api/portal/tickets'
import { Route as ApiPortalSubPortfoliosRouteImport } from './routes/api/portal/sub-portfolios'
import { Route as ApiPortalSubPortfolioHoldingsRouteImport } from './routes/api/portal/sub-portfolio-holdings'
import { Route as ApiPortalStaffTradeHistoryRouteImport } from './routes/api/portal/staff-trade-history'
import { Route as ApiPortalProfileRouteImport } from './routes/api/portal/profile'
import { Route as ApiPortalOnboardClientRouteImport } from './routes/api/portal/onboard-client'
import { Route as ApiPortalMyWalletsRouteImport } from './routes/api/portal/my-wallets'
import { Route as ApiPortalMfaRouteImport } from './routes/api/portal/mfa'
import { Route as ApiPortalInvestorTradingRouteImport } from './routes/api/portal/investor-trading'
import { Route as ApiPortalInvestorOnboardingRouteImport } from './routes/api/portal/investor-onboarding'
import { Route as ApiPortalFundingReviewRouteImport } from './routes/api/portal/funding-review'
import { Route as ApiPortalClientsAdminRouteImport } from './routes/api/portal/clients-admin'
import { Route as ApiPortalAuthDiagnosticsRouteImport } from './routes/api/portal/auth-diagnostics'
import { Route as ApiPortalAuditLogsRouteImport } from './routes/api/portal/audit-logs'
import { Route as ApiPortalAssetListingsRouteImport } from './routes/api/portal/asset-listings'
import { Route as ApiPortalAdminStaffRouteImport } from './routes/api/portal/admin-staff'
import { Route as PortalLoginAdminCreateAccountRouteImport } from './routes/portal.login.admin.create-account'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalDesksRoute = GlobalDesksRouteImport.update({
  id: '/global-desks',
  path: '/global-desks',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosuresRoute = DisclosuresRouteImport.update({
  id: '/disclosures',
  path: '/disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SymbolSlugRoute = SymbolSlugRouteImport.update({
  id: '/symbol/$slug',
  path: '/symbol/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTradeWorkspaceRoute = PortalTradeWorkspaceRouteImport.update({
  id: '/portal/trade-workspace',
  path: '/portal/trade-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalResetPasswordRoute = PortalResetPasswordRouteImport.update({
  id: '/portal/reset-password',
  path: '/portal/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalInvestorRoute = PortalInvestorRouteImport.update({
  id: '/portal/investor',
  path: '/portal/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/portal/admin',
  path: '/portal/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalInvestorIndexRoute = PortalInvestorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalInvestorRoute,
} as any)
const PortalAdminIndexRoute = PortalAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalSignupInvestorRoute = PortalSignupInvestorRouteImport.update({
  id: '/portal/signup_/investor',
  path: '/portal/signup/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginInvestorRoute = PortalLoginInvestorRouteImport.update({
  id: '/portal/login_/investor',
  path: '/portal/login/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginAdminRoute = PortalLoginAdminRouteImport.update({
  id: '/portal/login_/admin',
  path: '/portal/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalInvestorWalletRoute = PortalInvestorWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => PortalInvestorRoute,
} as any)
const PortalInvestorTransactionsRoute =
  PortalInvestorTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => PortalInvestorRoute,
  } as any)
const PortalInvestorTradeHistoryRoute =
  PortalInvestorTradeHistoryRouteImport.update({
    id: '/trade-history',
    path: '/trade-history',
    getParentRoute: () => PortalInvestorRoute,
  } as any)
const PortalInvestorTradeRoute = PortalInvestorTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => PortalInvestorRoute,
} as any)
const PortalInvestorSupportRoute = PortalInvestorSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PortalInvestorRoute,
} as any)
const PortalInvestorSettingsRoute = PortalInvestorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalInvestorRoute,
} as any)
const PortalInvestorProfileRoute = PortalInvestorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalInvestorRoute,
} as any)
const PortalInvestorPortfolioRoute = PortalInvestorPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => PortalInvestorRoute,
} as any)
const PortalInvestorPerformanceRoute =
  PortalInvestorPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => PortalInvestorRoute,
  } as any)
const PortalInvestorOnboardingRoute =
  PortalInvestorOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => PortalInvestorRoute,
  } as any)
const PortalInvestorKycRoute = PortalInvestorKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => PortalInvestorRoute,
} as any)
const PortalInvestorApplyRoute = PortalInvestorApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => PortalInvestorRoute,
} as any)
const PortalAdminTradeHistoryRoute = PortalAdminTradeHistoryRouteImport.update({
  id: '/trade-history',
  path: '/trade-history',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminStrategiesRoute = PortalAdminStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminRiskRoute = PortalAdminRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminOnboardingRoute = PortalAdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminGlobalDeskRoute = PortalAdminGlobalDeskRouteImport.update({
  id: '/global-desk',
  path: '/global-desk',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminFundingRoute = PortalAdminFundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminClientsRoute = PortalAdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminAuditRoute = PortalAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminAdminsRoute = PortalAdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => PortalAdminRoute,
} as any)
const ApiPublicTickerQuotesRoute = ApiPublicTickerQuotesRouteImport.update({
  id: '/api/public/ticker-quotes',
  path: '/api/public/ticker-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSymbolDetailRoute = ApiPublicSymbolDetailRouteImport.update({
  id: '/api/public/symbol-detail',
  path: '/api/public/symbol-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSchemaReadinessRoute =
  ApiPublicSchemaReadinessRouteImport.update({
    id: '/api/public/schema-readiness',
    path: '/api/public/schema-readiness',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicResolveLoginEmailRoute =
  ApiPublicResolveLoginEmailRouteImport.update({
    id: '/api/public/resolve-login-email',
    path: '/api/public/resolve-login-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaypalWebhookRoute = ApiPublicPaypalWebhookRouteImport.update({
  id: '/api/public/paypal-webhook',
  path: '/api/public/paypal-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveMarketQuotesRoute =
  ApiPublicLiveMarketQuotesRouteImport.update({
    id: '/api/public/live-market-quotes',
    path: '/api/public/live-market-quotes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLiveMarketNewsRoute = ApiPublicLiveMarketNewsRouteImport.update({
  id: '/api/public/live-market-news',
  path: '/api/public/live-market-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthHealthRoute = ApiPublicAuthHealthRouteImport.update({
  id: '/api/public/auth-health',
  path: '/api/public/auth-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAssetListingQuotesRoute =
  ApiPublicAssetListingQuotesRouteImport.update({
    id: '/api/public/asset-listing-quotes',
    path: '/api/public/asset-listing-quotes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSignupRoute = ApiPublicAdminSignupRouteImport.update({
  id: '/api/public/admin-signup',
  path: '/api/public/admin-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalWalletActionsRoute = ApiPortalWalletActionsRouteImport.update({
  id: '/api/portal/wallet-actions',
  path: '/api/portal/wallet-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalTradeHistoryRoute = ApiPortalTradeHistoryRouteImport.update({
  id: '/api/portal/trade-history',
  path: '/api/portal/trade-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalTicketsRoute = ApiPortalTicketsRouteImport.update({
  id: '/api/portal/tickets',
  path: '/api/portal/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalSubPortfoliosRoute = ApiPortalSubPortfoliosRouteImport.update({
  id: '/api/portal/sub-portfolios',
  path: '/api/portal/sub-portfolios',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalSubPortfolioHoldingsRoute =
  ApiPortalSubPortfolioHoldingsRouteImport.update({
    id: '/api/portal/sub-portfolio-holdings',
    path: '/api/portal/sub-portfolio-holdings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPortalStaffTradeHistoryRoute =
  ApiPortalStaffTradeHistoryRouteImport.update({
    id: '/api/portal/staff-trade-history',
    path: '/api/portal/staff-trade-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPortalProfileRoute = ApiPortalProfileRouteImport.update({
  id: '/api/portal/profile',
  path: '/api/portal/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalOnboardClientRoute = ApiPortalOnboardClientRouteImport.update({
  id: '/api/portal/onboard-client',
  path: '/api/portal/onboard-client',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalMyWalletsRoute = ApiPortalMyWalletsRouteImport.update({
  id: '/api/portal/my-wallets',
  path: '/api/portal/my-wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalMfaRoute = ApiPortalMfaRouteImport.update({
  id: '/api/portal/mfa',
  path: '/api/portal/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalInvestorTradingRoute =
  ApiPortalInvestorTradingRouteImport.update({
    id: '/api/portal/investor-trading',
    path: '/api/portal/investor-trading',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPortalInvestorOnboardingRoute =
  ApiPortalInvestorOnboardingRouteImport.update({
    id: '/api/portal/investor-onboarding',
    path: '/api/portal/investor-onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPortalFundingReviewRoute = ApiPortalFundingReviewRouteImport.update({
  id: '/api/portal/funding-review',
  path: '/api/portal/funding-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalClientsAdminRoute = ApiPortalClientsAdminRouteImport.update({
  id: '/api/portal/clients-admin',
  path: '/api/portal/clients-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalAuthDiagnosticsRoute =
  ApiPortalAuthDiagnosticsRouteImport.update({
    id: '/api/portal/auth-diagnostics',
    path: '/api/portal/auth-diagnostics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPortalAuditLogsRoute = ApiPortalAuditLogsRouteImport.update({
  id: '/api/portal/audit-logs',
  path: '/api/portal/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalAssetListingsRoute = ApiPortalAssetListingsRouteImport.update({
  id: '/api/portal/asset-listings',
  path: '/api/portal/asset-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalAdminStaffRoute = ApiPortalAdminStaffRouteImport.update({
  id: '/api/portal/admin-staff',
  path: '/api/portal/admin-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginAdminCreateAccountRoute =
  PortalLoginAdminCreateAccountRouteImport.update({
    id: '/admin/create-account',
    path: '/admin/create-account',
    getParentRoute: () => PortalLoginRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/disclosures': typeof DisclosuresRoute
  '/global-desks': typeof GlobalDesksRoute
  '/insights': typeof InsightsRoute
  '/markets': typeof MarketsRoute
  '/performance': typeof PerformanceRoute
  '/privacy': typeof PrivacyRoute
  '/strategies': typeof StrategiesRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/portal/admin': typeof PortalAdminRouteWithChildren
  '/portal/investor': typeof PortalInvestorRouteWithChildren
  '/portal/login': typeof PortalLoginRouteWithChildren
  '/portal/reset-password': typeof PortalResetPasswordRoute
  '/portal/trade-workspace': typeof PortalTradeWorkspaceRoute
  '/symbol/$slug': typeof SymbolSlugRoute
  '/api/portal/admin-staff': typeof ApiPortalAdminStaffRoute
  '/api/portal/asset-listings': typeof ApiPortalAssetListingsRoute
  '/api/portal/audit-logs': typeof ApiPortalAuditLogsRoute
  '/api/portal/auth-diagnostics': typeof ApiPortalAuthDiagnosticsRoute
  '/api/portal/clients-admin': typeof ApiPortalClientsAdminRoute
  '/api/portal/funding-review': typeof ApiPortalFundingReviewRoute
  '/api/portal/investor-onboarding': typeof ApiPortalInvestorOnboardingRoute
  '/api/portal/investor-trading': typeof ApiPortalInvestorTradingRoute
  '/api/portal/mfa': typeof ApiPortalMfaRoute
  '/api/portal/my-wallets': typeof ApiPortalMyWalletsRoute
  '/api/portal/onboard-client': typeof ApiPortalOnboardClientRoute
  '/api/portal/profile': typeof ApiPortalProfileRoute
  '/api/portal/staff-trade-history': typeof ApiPortalStaffTradeHistoryRoute
  '/api/portal/sub-portfolio-holdings': typeof ApiPortalSubPortfolioHoldingsRoute
  '/api/portal/sub-portfolios': typeof ApiPortalSubPortfoliosRoute
  '/api/portal/tickets': typeof ApiPortalTicketsRoute
  '/api/portal/trade-history': typeof ApiPortalTradeHistoryRoute
  '/api/portal/wallet-actions': typeof ApiPortalWalletActionsRoute
  '/api/public/admin-signup': typeof ApiPublicAdminSignupRoute
  '/api/public/asset-listing-quotes': typeof ApiPublicAssetListingQuotesRoute
  '/api/public/auth-health': typeof ApiPublicAuthHealthRoute
  '/api/public/live-market-news': typeof ApiPublicLiveMarketNewsRoute
  '/api/public/live-market-quotes': typeof ApiPublicLiveMarketQuotesRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
  '/api/public/resolve-login-email': typeof ApiPublicResolveLoginEmailRoute
  '/api/public/schema-readiness': typeof ApiPublicSchemaReadinessRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/symbol-detail': typeof ApiPublicSymbolDetailRoute
  '/api/public/ticker-quotes': typeof ApiPublicTickerQuotesRoute
  '/portal/admin/admins': typeof PortalAdminAdminsRoute
  '/portal/admin/audit': typeof PortalAdminAuditRoute
  '/portal/admin/clients': typeof PortalAdminClientsRoute
  '/portal/admin/funding': typeof PortalAdminFundingRoute
  '/portal/admin/global-desk': typeof PortalAdminGlobalDeskRoute
  '/portal/admin/onboarding': typeof PortalAdminOnboardingRoute
  '/portal/admin/risk': typeof PortalAdminRiskRoute
  '/portal/admin/strategies': typeof PortalAdminStrategiesRoute
  '/portal/admin/trade-history': typeof PortalAdminTradeHistoryRoute
  '/portal/investor/apply': typeof PortalInvestorApplyRoute
  '/portal/investor/kyc': typeof PortalInvestorKycRoute
  '/portal/investor/onboarding': typeof PortalInvestorOnboardingRoute
  '/portal/investor/performance': typeof PortalInvestorPerformanceRoute
  '/portal/investor/portfolio': typeof PortalInvestorPortfolioRoute
  '/portal/investor/profile': typeof PortalInvestorProfileRoute
  '/portal/investor/settings': typeof PortalInvestorSettingsRoute
  '/portal/investor/support': typeof PortalInvestorSupportRoute
  '/portal/investor/trade': typeof PortalInvestorTradeRoute
  '/portal/investor/trade-history': typeof PortalInvestorTradeHistoryRoute
  '/portal/investor/transactions': typeof PortalInvestorTransactionsRoute
  '/portal/investor/wallet': typeof PortalInvestorWalletRoute
  '/portal/login/admin': typeof PortalLoginAdminRoute
  '/portal/login/investor': typeof PortalLoginInvestorRoute
  '/portal/signup/investor': typeof PortalSignupInvestorRoute
  '/portal/admin/': typeof PortalAdminIndexRoute
  '/portal/investor/': typeof PortalInvestorIndexRoute
  '/portal/login/admin/create-account': typeof PortalLoginAdminCreateAccountRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/disclosures': typeof DisclosuresRoute
  '/global-desks': typeof GlobalDesksRoute
  '/insights': typeof InsightsRoute
  '/markets': typeof MarketsRoute
  '/performance': typeof PerformanceRoute
  '/privacy': typeof PrivacyRoute
  '/strategies': typeof StrategiesRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/portal/login': typeof PortalLoginRouteWithChildren
  '/portal/reset-password': typeof PortalResetPasswordRoute
  '/portal/trade-workspace': typeof PortalTradeWorkspaceRoute
  '/symbol/$slug': typeof SymbolSlugRoute
  '/api/portal/admin-staff': typeof ApiPortalAdminStaffRoute
  '/api/portal/asset-listings': typeof ApiPortalAssetListingsRoute
  '/api/portal/audit-logs': typeof ApiPortalAuditLogsRoute
  '/api/portal/auth-diagnostics': typeof ApiPortalAuthDiagnosticsRoute
  '/api/portal/clients-admin': typeof ApiPortalClientsAdminRoute
  '/api/portal/funding-review': typeof ApiPortalFundingReviewRoute
  '/api/portal/investor-onboarding': typeof ApiPortalInvestorOnboardingRoute
  '/api/portal/investor-trading': typeof ApiPortalInvestorTradingRoute
  '/api/portal/mfa': typeof ApiPortalMfaRoute
  '/api/portal/my-wallets': typeof ApiPortalMyWalletsRoute
  '/api/portal/onboard-client': typeof ApiPortalOnboardClientRoute
  '/api/portal/profile': typeof ApiPortalProfileRoute
  '/api/portal/staff-trade-history': typeof ApiPortalStaffTradeHistoryRoute
  '/api/portal/sub-portfolio-holdings': typeof ApiPortalSubPortfolioHoldingsRoute
  '/api/portal/sub-portfolios': typeof ApiPortalSubPortfoliosRoute
  '/api/portal/tickets': typeof ApiPortalTicketsRoute
  '/api/portal/trade-history': typeof ApiPortalTradeHistoryRoute
  '/api/portal/wallet-actions': typeof ApiPortalWalletActionsRoute
  '/api/public/admin-signup': typeof ApiPublicAdminSignupRoute
  '/api/public/asset-listing-quotes': typeof ApiPublicAssetListingQuotesRoute
  '/api/public/auth-health': typeof ApiPublicAuthHealthRoute
  '/api/public/live-market-news': typeof ApiPublicLiveMarketNewsRoute
  '/api/public/live-market-quotes': typeof ApiPublicLiveMarketQuotesRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
  '/api/public/resolve-login-email': typeof ApiPublicResolveLoginEmailRoute
  '/api/public/schema-readiness': typeof ApiPublicSchemaReadinessRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/symbol-detail': typeof ApiPublicSymbolDetailRoute
  '/api/public/ticker-quotes': typeof ApiPublicTickerQuotesRoute
  '/portal/admin/admins': typeof PortalAdminAdminsRoute
  '/portal/admin/audit': typeof PortalAdminAuditRoute
  '/portal/admin/clients': typeof PortalAdminClientsRoute
  '/portal/admin/funding': typeof PortalAdminFundingRoute
  '/portal/admin/global-desk': typeof PortalAdminGlobalDeskRoute
  '/portal/admin/onboarding': typeof PortalAdminOnboardingRoute
  '/portal/admin/risk': typeof PortalAdminRiskRoute
  '/portal/admin/strategies': typeof PortalAdminStrategiesRoute
  '/portal/admin/trade-history': typeof PortalAdminTradeHistoryRoute
  '/portal/investor/apply': typeof PortalInvestorApplyRoute
  '/portal/investor/kyc': typeof PortalInvestorKycRoute
  '/portal/investor/onboarding': typeof PortalInvestorOnboardingRoute
  '/portal/investor/performance': typeof PortalInvestorPerformanceRoute
  '/portal/investor/portfolio': typeof PortalInvestorPortfolioRoute
  '/portal/investor/profile': typeof PortalInvestorProfileRoute
  '/portal/investor/settings': typeof PortalInvestorSettingsRoute
  '/portal/investor/support': typeof PortalInvestorSupportRoute
  '/portal/investor/trade': typeof PortalInvestorTradeRoute
  '/portal/investor/trade-history': typeof PortalInvestorTradeHistoryRoute
  '/portal/investor/transactions': typeof PortalInvestorTransactionsRoute
  '/portal/investor/wallet': typeof PortalInvestorWalletRoute
  '/portal/login/admin': typeof PortalLoginAdminRoute
  '/portal/login/investor': typeof PortalLoginInvestorRoute
  '/portal/signup/investor': typeof PortalSignupInvestorRoute
  '/portal/admin': typeof PortalAdminIndexRoute
  '/portal/investor': typeof PortalInvestorIndexRoute
  '/portal/login/admin/create-account': typeof PortalLoginAdminCreateAccountRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/disclosures': typeof DisclosuresRoute
  '/global-desks': typeof GlobalDesksRoute
  '/insights': typeof InsightsRoute
  '/markets': typeof MarketsRoute
  '/performance': typeof PerformanceRoute
  '/privacy': typeof PrivacyRoute
  '/strategies': typeof StrategiesRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/portal/admin': typeof PortalAdminRouteWithChildren
  '/portal/investor': typeof PortalInvestorRouteWithChildren
  '/portal/login': typeof PortalLoginRouteWithChildren
  '/portal/reset-password': typeof PortalResetPasswordRoute
  '/portal/trade-workspace': typeof PortalTradeWorkspaceRoute
  '/symbol/$slug': typeof SymbolSlugRoute
  '/api/portal/admin-staff': typeof ApiPortalAdminStaffRoute
  '/api/portal/asset-listings': typeof ApiPortalAssetListingsRoute
  '/api/portal/audit-logs': typeof ApiPortalAuditLogsRoute
  '/api/portal/auth-diagnostics': typeof ApiPortalAuthDiagnosticsRoute
  '/api/portal/clients-admin': typeof ApiPortalClientsAdminRoute
  '/api/portal/funding-review': typeof ApiPortalFundingReviewRoute
  '/api/portal/investor-onboarding': typeof ApiPortalInvestorOnboardingRoute
  '/api/portal/investor-trading': typeof ApiPortalInvestorTradingRoute
  '/api/portal/mfa': typeof ApiPortalMfaRoute
  '/api/portal/my-wallets': typeof ApiPortalMyWalletsRoute
  '/api/portal/onboard-client': typeof ApiPortalOnboardClientRoute
  '/api/portal/profile': typeof ApiPortalProfileRoute
  '/api/portal/staff-trade-history': typeof ApiPortalStaffTradeHistoryRoute
  '/api/portal/sub-portfolio-holdings': typeof ApiPortalSubPortfolioHoldingsRoute
  '/api/portal/sub-portfolios': typeof ApiPortalSubPortfoliosRoute
  '/api/portal/tickets': typeof ApiPortalTicketsRoute
  '/api/portal/trade-history': typeof ApiPortalTradeHistoryRoute
  '/api/portal/wallet-actions': typeof ApiPortalWalletActionsRoute
  '/api/public/admin-signup': typeof ApiPublicAdminSignupRoute
  '/api/public/asset-listing-quotes': typeof ApiPublicAssetListingQuotesRoute
  '/api/public/auth-health': typeof ApiPublicAuthHealthRoute
  '/api/public/live-market-news': typeof ApiPublicLiveMarketNewsRoute
  '/api/public/live-market-quotes': typeof ApiPublicLiveMarketQuotesRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
  '/api/public/resolve-login-email': typeof ApiPublicResolveLoginEmailRoute
  '/api/public/schema-readiness': typeof ApiPublicSchemaReadinessRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/symbol-detail': typeof ApiPublicSymbolDetailRoute
  '/api/public/ticker-quotes': typeof ApiPublicTickerQuotesRoute
  '/portal/admin/admins': typeof PortalAdminAdminsRoute
  '/portal/admin/audit': typeof PortalAdminAuditRoute
  '/portal/admin/clients': typeof PortalAdminClientsRoute
  '/portal/admin/funding': typeof PortalAdminFundingRoute
  '/portal/admin/global-desk': typeof PortalAdminGlobalDeskRoute
  '/portal/admin/onboarding': typeof PortalAdminOnboardingRoute
  '/portal/admin/risk': typeof PortalAdminRiskRoute
  '/portal/admin/strategies': typeof PortalAdminStrategiesRoute
  '/portal/admin/trade-history': typeof PortalAdminTradeHistoryRoute
  '/portal/investor/apply': typeof PortalInvestorApplyRoute
  '/portal/investor/kyc': typeof PortalInvestorKycRoute
  '/portal/investor/onboarding': typeof PortalInvestorOnboardingRoute
  '/portal/investor/performance': typeof PortalInvestorPerformanceRoute
  '/portal/investor/portfolio': typeof PortalInvestorPortfolioRoute
  '/portal/investor/profile': typeof PortalInvestorProfileRoute
  '/portal/investor/settings': typeof PortalInvestorSettingsRoute
  '/portal/investor/support': typeof PortalInvestorSupportRoute
  '/portal/investor/trade': typeof PortalInvestorTradeRoute
  '/portal/investor/trade-history': typeof PortalInvestorTradeHistoryRoute
  '/portal/investor/transactions': typeof PortalInvestorTransactionsRoute
  '/portal/investor/wallet': typeof PortalInvestorWalletRoute
  '/portal/login_/admin': typeof PortalLoginAdminRoute
  '/portal/login_/investor': typeof PortalLoginInvestorRoute
  '/portal/signup_/investor': typeof PortalSignupInvestorRoute
  '/portal/admin/': typeof PortalAdminIndexRoute
  '/portal/investor/': typeof PortalInvestorIndexRoute
  '/portal/login/admin/create-account': typeof PortalLoginAdminCreateAccountRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/approach'
    | '/careers'
    | '/contact'
    | '/disclosures'
    | '/global-desks'
    | '/insights'
    | '/markets'
    | '/performance'
    | '/privacy'
    | '/strategies'
    | '/technology'
    | '/terms'
    | '/auth/confirm'
    | '/portal/admin'
    | '/portal/investor'
    | '/portal/login'
    | '/portal/reset-password'
    | '/portal/trade-workspace'
    | '/symbol/$slug'
    | '/api/portal/admin-staff'
    | '/api/portal/asset-listings'
    | '/api/portal/audit-logs'
    | '/api/portal/auth-diagnostics'
    | '/api/portal/clients-admin'
    | '/api/portal/funding-review'
    | '/api/portal/investor-onboarding'
    | '/api/portal/investor-trading'
    | '/api/portal/mfa'
    | '/api/portal/my-wallets'
    | '/api/portal/onboard-client'
    | '/api/portal/profile'
    | '/api/portal/staff-trade-history'
    | '/api/portal/sub-portfolio-holdings'
    | '/api/portal/sub-portfolios'
    | '/api/portal/tickets'
    | '/api/portal/trade-history'
    | '/api/portal/wallet-actions'
    | '/api/public/admin-signup'
    | '/api/public/asset-listing-quotes'
    | '/api/public/auth-health'
    | '/api/public/live-market-news'
    | '/api/public/live-market-quotes'
    | '/api/public/paypal-webhook'
    | '/api/public/resolve-login-email'
    | '/api/public/schema-readiness'
    | '/api/public/stripe-webhook'
    | '/api/public/symbol-detail'
    | '/api/public/ticker-quotes'
    | '/portal/admin/admins'
    | '/portal/admin/audit'
    | '/portal/admin/clients'
    | '/portal/admin/funding'
    | '/portal/admin/global-desk'
    | '/portal/admin/onboarding'
    | '/portal/admin/risk'
    | '/portal/admin/strategies'
    | '/portal/admin/trade-history'
    | '/portal/investor/apply'
    | '/portal/investor/kyc'
    | '/portal/investor/onboarding'
    | '/portal/investor/performance'
    | '/portal/investor/portfolio'
    | '/portal/investor/profile'
    | '/portal/investor/settings'
    | '/portal/investor/support'
    | '/portal/investor/trade'
    | '/portal/investor/trade-history'
    | '/portal/investor/transactions'
    | '/portal/investor/wallet'
    | '/portal/login/admin'
    | '/portal/login/investor'
    | '/portal/signup/investor'
    | '/portal/admin/'
    | '/portal/investor/'
    | '/portal/login/admin/create-account'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/approach'
    | '/careers'
    | '/contact'
    | '/disclosures'
    | '/global-desks'
    | '/insights'
    | '/markets'
    | '/performance'
    | '/privacy'
    | '/strategies'
    | '/technology'
    | '/terms'
    | '/auth/confirm'
    | '/portal/login'
    | '/portal/reset-password'
    | '/portal/trade-workspace'
    | '/symbol/$slug'
    | '/api/portal/admin-staff'
    | '/api/portal/asset-listings'
    | '/api/portal/audit-logs'
    | '/api/portal/auth-diagnostics'
    | '/api/portal/clients-admin'
    | '/api/portal/funding-review'
    | '/api/portal/investor-onboarding'
    | '/api/portal/investor-trading'
    | '/api/portal/mfa'
    | '/api/portal/my-wallets'
    | '/api/portal/onboard-client'
    | '/api/portal/profile'
    | '/api/portal/staff-trade-history'
    | '/api/portal/sub-portfolio-holdings'
    | '/api/portal/sub-portfolios'
    | '/api/portal/tickets'
    | '/api/portal/trade-history'
    | '/api/portal/wallet-actions'
    | '/api/public/admin-signup'
    | '/api/public/asset-listing-quotes'
    | '/api/public/auth-health'
    | '/api/public/live-market-news'
    | '/api/public/live-market-quotes'
    | '/api/public/paypal-webhook'
    | '/api/public/resolve-login-email'
    | '/api/public/schema-readiness'
    | '/api/public/stripe-webhook'
    | '/api/public/symbol-detail'
    | '/api/public/ticker-quotes'
    | '/portal/admin/admins'
    | '/portal/admin/audit'
    | '/portal/admin/clients'
    | '/portal/admin/funding'
    | '/portal/admin/global-desk'
    | '/portal/admin/onboarding'
    | '/portal/admin/risk'
    | '/portal/admin/strategies'
    | '/portal/admin/trade-history'
    | '/portal/investor/apply'
    | '/portal/investor/kyc'
    | '/portal/investor/onboarding'
    | '/portal/investor/performance'
    | '/portal/investor/portfolio'
    | '/portal/investor/profile'
    | '/portal/investor/settings'
    | '/portal/investor/support'
    | '/portal/investor/trade'
    | '/portal/investor/trade-history'
    | '/portal/investor/transactions'
    | '/portal/investor/wallet'
    | '/portal/login/admin'
    | '/portal/login/investor'
    | '/portal/signup/investor'
    | '/portal/admin'
    | '/portal/investor'
    | '/portal/login/admin/create-account'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/approach'
    | '/careers'
    | '/contact'
    | '/disclosures'
    | '/global-desks'
    | '/insights'
    | '/markets'
    | '/performance'
    | '/privacy'
    | '/strategies'
    | '/technology'
    | '/terms'
    | '/auth/confirm'
    | '/portal/admin'
    | '/portal/investor'
    | '/portal/login'
    | '/portal/reset-password'
    | '/portal/trade-workspace'
    | '/symbol/$slug'
    | '/api/portal/admin-staff'
    | '/api/portal/asset-listings'
    | '/api/portal/audit-logs'
    | '/api/portal/auth-diagnostics'
    | '/api/portal/clients-admin'
    | '/api/portal/funding-review'
    | '/api/portal/investor-onboarding'
    | '/api/portal/investor-trading'
    | '/api/portal/mfa'
    | '/api/portal/my-wallets'
    | '/api/portal/onboard-client'
    | '/api/portal/profile'
    | '/api/portal/staff-trade-history'
    | '/api/portal/sub-portfolio-holdings'
    | '/api/portal/sub-portfolios'
    | '/api/portal/tickets'
    | '/api/portal/trade-history'
    | '/api/portal/wallet-actions'
    | '/api/public/admin-signup'
    | '/api/public/asset-listing-quotes'
    | '/api/public/auth-health'
    | '/api/public/live-market-news'
    | '/api/public/live-market-quotes'
    | '/api/public/paypal-webhook'
    | '/api/public/resolve-login-email'
    | '/api/public/schema-readiness'
    | '/api/public/stripe-webhook'
    | '/api/public/symbol-detail'
    | '/api/public/ticker-quotes'
    | '/portal/admin/admins'
    | '/portal/admin/audit'
    | '/portal/admin/clients'
    | '/portal/admin/funding'
    | '/portal/admin/global-desk'
    | '/portal/admin/onboarding'
    | '/portal/admin/risk'
    | '/portal/admin/strategies'
    | '/portal/admin/trade-history'
    | '/portal/investor/apply'
    | '/portal/investor/kyc'
    | '/portal/investor/onboarding'
    | '/portal/investor/performance'
    | '/portal/investor/portfolio'
    | '/portal/investor/profile'
    | '/portal/investor/settings'
    | '/portal/investor/support'
    | '/portal/investor/trade'
    | '/portal/investor/trade-history'
    | '/portal/investor/transactions'
    | '/portal/investor/wallet'
    | '/portal/login_/admin'
    | '/portal/login_/investor'
    | '/portal/signup_/investor'
    | '/portal/admin/'
    | '/portal/investor/'
    | '/portal/login/admin/create-account'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DisclosuresRoute: typeof DisclosuresRoute
  GlobalDesksRoute: typeof GlobalDesksRoute
  InsightsRoute: typeof InsightsRoute
  MarketsRoute: typeof MarketsRoute
  PerformanceRoute: typeof PerformanceRoute
  PrivacyRoute: typeof PrivacyRoute
  StrategiesRoute: typeof StrategiesRoute
  TechnologyRoute: typeof TechnologyRoute
  TermsRoute: typeof TermsRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  PortalAdminRoute: typeof PortalAdminRouteWithChildren
  PortalInvestorRoute: typeof PortalInvestorRouteWithChildren
  PortalLoginRoute: typeof PortalLoginRouteWithChildren
  PortalResetPasswordRoute: typeof PortalResetPasswordRoute
  PortalTradeWorkspaceRoute: typeof PortalTradeWorkspaceRoute
  SymbolSlugRoute: typeof SymbolSlugRoute
  ApiPortalAdminStaffRoute: typeof ApiPortalAdminStaffRoute
  ApiPortalAssetListingsRoute: typeof ApiPortalAssetListingsRoute
  ApiPortalAuditLogsRoute: typeof ApiPortalAuditLogsRoute
  ApiPortalAuthDiagnosticsRoute: typeof ApiPortalAuthDiagnosticsRoute
  ApiPortalClientsAdminRoute: typeof ApiPortalClientsAdminRoute
  ApiPortalFundingReviewRoute: typeof ApiPortalFundingReviewRoute
  ApiPortalInvestorOnboardingRoute: typeof ApiPortalInvestorOnboardingRoute
  ApiPortalInvestorTradingRoute: typeof ApiPortalInvestorTradingRoute
  ApiPortalMfaRoute: typeof ApiPortalMfaRoute
  ApiPortalMyWalletsRoute: typeof ApiPortalMyWalletsRoute
  ApiPortalOnboardClientRoute: typeof ApiPortalOnboardClientRoute
  ApiPortalProfileRoute: typeof ApiPortalProfileRoute
  ApiPortalStaffTradeHistoryRoute: typeof ApiPortalStaffTradeHistoryRoute
  ApiPortalSubPortfolioHoldingsRoute: typeof ApiPortalSubPortfolioHoldingsRoute
  ApiPortalSubPortfoliosRoute: typeof ApiPortalSubPortfoliosRoute
  ApiPortalTicketsRoute: typeof ApiPortalTicketsRoute
  ApiPortalTradeHistoryRoute: typeof ApiPortalTradeHistoryRoute
  ApiPortalWalletActionsRoute: typeof ApiPortalWalletActionsRoute
  ApiPublicAdminSignupRoute: typeof ApiPublicAdminSignupRoute
  ApiPublicAssetListingQuotesRoute: typeof ApiPublicAssetListingQuotesRoute
  ApiPublicAuthHealthRoute: typeof ApiPublicAuthHealthRoute
  ApiPublicLiveMarketNewsRoute: typeof ApiPublicLiveMarketNewsRoute
  ApiPublicLiveMarketQuotesRoute: typeof ApiPublicLiveMarketQuotesRoute
  ApiPublicPaypalWebhookRoute: typeof ApiPublicPaypalWebhookRoute
  ApiPublicResolveLoginEmailRoute: typeof ApiPublicResolveLoginEmailRoute
  ApiPublicSchemaReadinessRoute: typeof ApiPublicSchemaReadinessRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicSymbolDetailRoute: typeof ApiPublicSymbolDetailRoute
  ApiPublicTickerQuotesRoute: typeof ApiPublicTickerQuotesRoute
  PortalLoginAdminRoute: typeof PortalLoginAdminRoute
  PortalLoginInvestorRoute: typeof PortalLoginInvestorRoute
  PortalSignupInvestorRoute: typeof PortalSignupInvestorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-desks': {
      id: '/global-desks'
      path: '/global-desks'
      fullPath: '/global-desks'
      preLoaderRoute: typeof GlobalDesksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosures': {
      id: '/disclosures'
      path: '/disclosures'
      fullPath: '/disclosures'
      preLoaderRoute: typeof DisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symbol/$slug': {
      id: '/symbol/$slug'
      path: '/symbol/$slug'
      fullPath: '/symbol/$slug'
      preLoaderRoute: typeof SymbolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/trade-workspace': {
      id: '/portal/trade-workspace'
      path: '/portal/trade-workspace'
      fullPath: '/portal/trade-workspace'
      preLoaderRoute: typeof PortalTradeWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/reset-password': {
      id: '/portal/reset-password'
      path: '/portal/reset-password'
      fullPath: '/portal/reset-password'
      preLoaderRoute: typeof PortalResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/investor': {
      id: '/portal/investor'
      path: '/portal/investor'
      fullPath: '/portal/investor'
      preLoaderRoute: typeof PortalInvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/admin': {
      id: '/portal/admin'
      path: '/portal/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/investor/': {
      id: '/portal/investor/'
      path: '/'
      fullPath: '/portal/investor/'
      preLoaderRoute: typeof PortalInvestorIndexRouteImport
      parentRoute: typeof PortalInvestorRoute
    }
    '/portal/admin/': {
      id: '/portal/admin/'
      path: '/'
      fullPath: '/portal/admin/'
      preLoaderRoute: typeof PortalAdminIndexRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/signup_/investor': {
      id: '/portal/signup_/investor'
      path: '/portal/signup/investor'
      fullPath: '/portal/signup/investor'
      preLoaderRoute: typeof PortalSignupInvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login_/investor': {
      id: '/portal/login_/investor'
      path: '/portal/login/investor'
      fullPath: '/portal/login/investor'
      preLoaderRoute: typeof PortalLoginInvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login_/admin': {
      id: '/portal/login_/admin'
      path: '/portal/login/admin'
      fullPath: '/portal/login/admin'
      preLoaderRoute: typeof PortalLoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/investor/wallet': {
      id: '/portal/investor/wallet'
      path: '/wallet'
      fullPath: '/portal/investor/wallet'
      preLoaderRoute: typeof PortalInvestorWalletRouteImport
      parentRoute: typeof PortalInvestorRoute
    }
    '/portal/investor/transactions': {
      id: '/portal/investor/transactions'
      path: '/transactions'
      fullPath: '/portal/investor/transactions'
      preLoaderRoute: typeof PortalInvestorTransactionsRouteImport
      parentRoute: typeof PortalInvestorRoute
    }
    '/portal/investor/trade-history': {
      id: '/portal/investor/trade-history'
      path: '/trade-history'
      fullPath: '/portal/investor/trade-history'
      preLoaderRoute: typeof PortalInvestorTradeHistoryRouteImport
      parentRoute: typeof PortalInvestorRoute
    }
    '/portal/investor/trade': {
      id: '/portal/investor/trade'
      path: '/trade'
      fullPath: '/portal/investor/trade'
      preLoaderRoute: typeof PortalInvestorTradeRouteImport
      parentRoute: typeof PortalInvestorRoute
    }
    '/portal/investor/support': {
      id: '/portal/investor/support'
      path: '/support'
      fullPath: '/portal/investor/support'
      preLoaderRoute: typeof PortalInvestorSupportRouteImport
      parentRoute: typeof PortalInvestorRoute
    }
    '/portal/investor/settings': {
      id: '/portal/investor/settings'
      path: '/settings'
      fullPath: '/portal/investor/settings'
      preLoaderRoute: typeof PortalInvestorSettingsRouteImport
      parentRoute: typeof PortalInvestorRoute
    }
    '/portal/investor/profile': {
      id: '/portal/investor/profile'
      path: '/profile'
      fullPath: '/portal/investor/profile'
      preLoaderRoute: typeof PortalInvestorProfileRouteImport
      parentRoute: typeof PortalInvestorRoute
    }
    '/portal/investor/portfolio': {
      id: '/portal/investor/portfolio'
      path: '/portfolio'
      fullPath: '/portal/investor/portfolio'
      preLoaderRoute: typeof PortalInvestorPortfolioRouteImport
      parentRoute: typeof PortalInvestorRoute
    }
    '/portal/investor/performance': {
      id: '/portal/investor/performance'
      path: '/performance'
      fullPath: '/portal/investor/performance'
      preLoaderRoute: typeof PortalInvestorPerformanceRouteImport
      parentRoute: typeof PortalInvestorRoute
    }
    '/portal/investor/onboarding': {
      id: '/portal/investor/onboarding'
      path: '/onboarding'
      fullPath: '/portal/investor/onboarding'
      preLoaderRoute: typeof PortalInvestorOnboardingRouteImport
      parentRoute: typeof PortalInvestorRoute
    }
    '/portal/investor/kyc': {
      id: '/portal/investor/kyc'
      path: '/kyc'
      fullPath: '/portal/investor/kyc'
      preLoaderRoute: typeof PortalInvestorKycRouteImport
      parentRoute: typeof PortalInvestorRoute
    }
    '/portal/investor/apply': {
      id: '/portal/investor/apply'
      path: '/apply'
      fullPath: '/portal/investor/apply'
      preLoaderRoute: typeof PortalInvestorApplyRouteImport
      parentRoute: typeof PortalInvestorRoute
    }
    '/portal/admin/trade-history': {
      id: '/portal/admin/trade-history'
      path: '/trade-history'
      fullPath: '/portal/admin/trade-history'
      preLoaderRoute: typeof PortalAdminTradeHistoryRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/strategies': {
      id: '/portal/admin/strategies'
      path: '/strategies'
      fullPath: '/portal/admin/strategies'
      preLoaderRoute: typeof PortalAdminStrategiesRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/risk': {
      id: '/portal/admin/risk'
      path: '/risk'
      fullPath: '/portal/admin/risk'
      preLoaderRoute: typeof PortalAdminRiskRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/onboarding': {
      id: '/portal/admin/onboarding'
      path: '/onboarding'
      fullPath: '/portal/admin/onboarding'
      preLoaderRoute: typeof PortalAdminOnboardingRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/global-desk': {
      id: '/portal/admin/global-desk'
      path: '/global-desk'
      fullPath: '/portal/admin/global-desk'
      preLoaderRoute: typeof PortalAdminGlobalDeskRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/funding': {
      id: '/portal/admin/funding'
      path: '/funding'
      fullPath: '/portal/admin/funding'
      preLoaderRoute: typeof PortalAdminFundingRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/clients': {
      id: '/portal/admin/clients'
      path: '/clients'
      fullPath: '/portal/admin/clients'
      preLoaderRoute: typeof PortalAdminClientsRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/audit': {
      id: '/portal/admin/audit'
      path: '/audit'
      fullPath: '/portal/admin/audit'
      preLoaderRoute: typeof PortalAdminAuditRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/admins': {
      id: '/portal/admin/admins'
      path: '/admins'
      fullPath: '/portal/admin/admins'
      preLoaderRoute: typeof PortalAdminAdminsRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/api/public/ticker-quotes': {
      id: '/api/public/ticker-quotes'
      path: '/api/public/ticker-quotes'
      fullPath: '/api/public/ticker-quotes'
      preLoaderRoute: typeof ApiPublicTickerQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/symbol-detail': {
      id: '/api/public/symbol-detail'
      path: '/api/public/symbol-detail'
      fullPath: '/api/public/symbol-detail'
      preLoaderRoute: typeof ApiPublicSymbolDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/schema-readiness': {
      id: '/api/public/schema-readiness'
      path: '/api/public/schema-readiness'
      fullPath: '/api/public/schema-readiness'
      preLoaderRoute: typeof ApiPublicSchemaReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resolve-login-email': {
      id: '/api/public/resolve-login-email'
      path: '/api/public/resolve-login-email'
      fullPath: '/api/public/resolve-login-email'
      preLoaderRoute: typeof ApiPublicResolveLoginEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal-webhook': {
      id: '/api/public/paypal-webhook'
      path: '/api/public/paypal-webhook'
      fullPath: '/api/public/paypal-webhook'
      preLoaderRoute: typeof ApiPublicPaypalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live-market-quotes': {
      id: '/api/public/live-market-quotes'
      path: '/api/public/live-market-quotes'
      fullPath: '/api/public/live-market-quotes'
      preLoaderRoute: typeof ApiPublicLiveMarketQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live-market-news': {
      id: '/api/public/live-market-news'
      path: '/api/public/live-market-news'
      fullPath: '/api/public/live-market-news'
      preLoaderRoute: typeof ApiPublicLiveMarketNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth-health': {
      id: '/api/public/auth-health'
      path: '/api/public/auth-health'
      fullPath: '/api/public/auth-health'
      preLoaderRoute: typeof ApiPublicAuthHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asset-listing-quotes': {
      id: '/api/public/asset-listing-quotes'
      path: '/api/public/asset-listing-quotes'
      fullPath: '/api/public/asset-listing-quotes'
      preLoaderRoute: typeof ApiPublicAssetListingQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-signup': {
      id: '/api/public/admin-signup'
      path: '/api/public/admin-signup'
      fullPath: '/api/public/admin-signup'
      preLoaderRoute: typeof ApiPublicAdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/wallet-actions': {
      id: '/api/portal/wallet-actions'
      path: '/api/portal/wallet-actions'
      fullPath: '/api/portal/wallet-actions'
      preLoaderRoute: typeof ApiPortalWalletActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/trade-history': {
      id: '/api/portal/trade-history'
      path: '/api/portal/trade-history'
      fullPath: '/api/portal/trade-history'
      preLoaderRoute: typeof ApiPortalTradeHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/tickets': {
      id: '/api/portal/tickets'
      path: '/api/portal/tickets'
      fullPath: '/api/portal/tickets'
      preLoaderRoute: typeof ApiPortalTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/sub-portfolios': {
      id: '/api/portal/sub-portfolios'
      path: '/api/portal/sub-portfolios'
      fullPath: '/api/portal/sub-portfolios'
      preLoaderRoute: typeof ApiPortalSubPortfoliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/sub-portfolio-holdings': {
      id: '/api/portal/sub-portfolio-holdings'
      path: '/api/portal/sub-portfolio-holdings'
      fullPath: '/api/portal/sub-portfolio-holdings'
      preLoaderRoute: typeof ApiPortalSubPortfolioHoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/staff-trade-history': {
      id: '/api/portal/staff-trade-history'
      path: '/api/portal/staff-trade-history'
      fullPath: '/api/portal/staff-trade-history'
      preLoaderRoute: typeof ApiPortalStaffTradeHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/profile': {
      id: '/api/portal/profile'
      path: '/api/portal/profile'
      fullPath: '/api/portal/profile'
      preLoaderRoute: typeof ApiPortalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/onboard-client': {
      id: '/api/portal/onboard-client'
      path: '/api/portal/onboard-client'
      fullPath: '/api/portal/onboard-client'
      preLoaderRoute: typeof ApiPortalOnboardClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/my-wallets': {
      id: '/api/portal/my-wallets'
      path: '/api/portal/my-wallets'
      fullPath: '/api/portal/my-wallets'
      preLoaderRoute: typeof ApiPortalMyWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/mfa': {
      id: '/api/portal/mfa'
      path: '/api/portal/mfa'
      fullPath: '/api/portal/mfa'
      preLoaderRoute: typeof ApiPortalMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/investor-trading': {
      id: '/api/portal/investor-trading'
      path: '/api/portal/investor-trading'
      fullPath: '/api/portal/investor-trading'
      preLoaderRoute: typeof ApiPortalInvestorTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/investor-onboarding': {
      id: '/api/portal/investor-onboarding'
      path: '/api/portal/investor-onboarding'
      fullPath: '/api/portal/investor-onboarding'
      preLoaderRoute: typeof ApiPortalInvestorOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/funding-review': {
      id: '/api/portal/funding-review'
      path: '/api/portal/funding-review'
      fullPath: '/api/portal/funding-review'
      preLoaderRoute: typeof ApiPortalFundingReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/clients-admin': {
      id: '/api/portal/clients-admin'
      path: '/api/portal/clients-admin'
      fullPath: '/api/portal/clients-admin'
      preLoaderRoute: typeof ApiPortalClientsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/auth-diagnostics': {
      id: '/api/portal/auth-diagnostics'
      path: '/api/portal/auth-diagnostics'
      fullPath: '/api/portal/auth-diagnostics'
      preLoaderRoute: typeof ApiPortalAuthDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/audit-logs': {
      id: '/api/portal/audit-logs'
      path: '/api/portal/audit-logs'
      fullPath: '/api/portal/audit-logs'
      preLoaderRoute: typeof ApiPortalAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/asset-listings': {
      id: '/api/portal/asset-listings'
      path: '/api/portal/asset-listings'
      fullPath: '/api/portal/asset-listings'
      preLoaderRoute: typeof ApiPortalAssetListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/admin-staff': {
      id: '/api/portal/admin-staff'
      path: '/api/portal/admin-staff'
      fullPath: '/api/portal/admin-staff'
      preLoaderRoute: typeof ApiPortalAdminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login/admin/create-account': {
      id: '/portal/login/admin/create-account'
      path: '/admin/create-account'
      fullPath: '/portal/login/admin/create-account'
      preLoaderRoute: typeof PortalLoginAdminCreateAccountRouteImport
      parentRoute: typeof PortalLoginRoute
    }
  }
}

interface PortalAdminRouteChildren {
  PortalAdminAdminsRoute: typeof PortalAdminAdminsRoute
  PortalAdminAuditRoute: typeof PortalAdminAuditRoute
  PortalAdminClientsRoute: typeof PortalAdminClientsRoute
  PortalAdminFundingRoute: typeof PortalAdminFundingRoute
  PortalAdminGlobalDeskRoute: typeof PortalAdminGlobalDeskRoute
  PortalAdminOnboardingRoute: typeof PortalAdminOnboardingRoute
  PortalAdminRiskRoute: typeof PortalAdminRiskRoute
  PortalAdminStrategiesRoute: typeof PortalAdminStrategiesRoute
  PortalAdminTradeHistoryRoute: typeof PortalAdminTradeHistoryRoute
  PortalAdminIndexRoute: typeof PortalAdminIndexRoute
}

const PortalAdminRouteChildren: PortalAdminRouteChildren = {
  PortalAdminAdminsRoute: PortalAdminAdminsRoute,
  PortalAdminAuditRoute: PortalAdminAuditRoute,
  PortalAdminClientsRoute: PortalAdminClientsRoute,
  PortalAdminFundingRoute: PortalAdminFundingRoute,
  PortalAdminGlobalDeskRoute: PortalAdminGlobalDeskRoute,
  PortalAdminOnboardingRoute: PortalAdminOnboardingRoute,
  PortalAdminRiskRoute: PortalAdminRiskRoute,
  PortalAdminStrategiesRoute: PortalAdminStrategiesRoute,
  PortalAdminTradeHistoryRoute: PortalAdminTradeHistoryRoute,
  PortalAdminIndexRoute: PortalAdminIndexRoute,
}

const PortalAdminRouteWithChildren = PortalAdminRoute._addFileChildren(
  PortalAdminRouteChildren,
)

interface PortalInvestorRouteChildren {
  PortalInvestorApplyRoute: typeof PortalInvestorApplyRoute
  PortalInvestorKycRoute: typeof PortalInvestorKycRoute
  PortalInvestorOnboardingRoute: typeof PortalInvestorOnboardingRoute
  PortalInvestorPerformanceRoute: typeof PortalInvestorPerformanceRoute
  PortalInvestorPortfolioRoute: typeof PortalInvestorPortfolioRoute
  PortalInvestorProfileRoute: typeof PortalInvestorProfileRoute
  PortalInvestorSettingsRoute: typeof PortalInvestorSettingsRoute
  PortalInvestorSupportRoute: typeof PortalInvestorSupportRoute
  PortalInvestorTradeRoute: typeof PortalInvestorTradeRoute
  PortalInvestorTradeHistoryRoute: typeof PortalInvestorTradeHistoryRoute
  PortalInvestorTransactionsRoute: typeof PortalInvestorTransactionsRoute
  PortalInvestorWalletRoute: typeof PortalInvestorWalletRoute
  PortalInvestorIndexRoute: typeof PortalInvestorIndexRoute
}

const PortalInvestorRouteChildren: PortalInvestorRouteChildren = {
  PortalInvestorApplyRoute: PortalInvestorApplyRoute,
  PortalInvestorKycRoute: PortalInvestorKycRoute,
  PortalInvestorOnboardingRoute: PortalInvestorOnboardingRoute,
  PortalInvestorPerformanceRoute: PortalInvestorPerformanceRoute,
  PortalInvestorPortfolioRoute: PortalInvestorPortfolioRoute,
  PortalInvestorProfileRoute: PortalInvestorProfileRoute,
  PortalInvestorSettingsRoute: PortalInvestorSettingsRoute,
  PortalInvestorSupportRoute: PortalInvestorSupportRoute,
  PortalInvestorTradeRoute: PortalInvestorTradeRoute,
  PortalInvestorTradeHistoryRoute: PortalInvestorTradeHistoryRoute,
  PortalInvestorTransactionsRoute: PortalInvestorTransactionsRoute,
  PortalInvestorWalletRoute: PortalInvestorWalletRoute,
  PortalInvestorIndexRoute: PortalInvestorIndexRoute,
}

const PortalInvestorRouteWithChildren = PortalInvestorRoute._addFileChildren(
  PortalInvestorRouteChildren,
)

interface PortalLoginRouteChildren {
  PortalLoginAdminCreateAccountRoute: typeof PortalLoginAdminCreateAccountRoute
}

const PortalLoginRouteChildren: PortalLoginRouteChildren = {
  PortalLoginAdminCreateAccountRoute: PortalLoginAdminCreateAccountRoute,
}

const PortalLoginRouteWithChildren = PortalLoginRoute._addFileChildren(
  PortalLoginRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DisclosuresRoute: DisclosuresRoute,
  GlobalDesksRoute: GlobalDesksRoute,
  InsightsRoute: InsightsRoute,
  MarketsRoute: MarketsRoute,
  PerformanceRoute: PerformanceRoute,
  PrivacyRoute: PrivacyRoute,
  StrategiesRoute: StrategiesRoute,
  TechnologyRoute: TechnologyRoute,
  TermsRoute: TermsRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  PortalAdminRoute: PortalAdminRouteWithChildren,
  PortalInvestorRoute: PortalInvestorRouteWithChildren,
  PortalLoginRoute: PortalLoginRouteWithChildren,
  PortalResetPasswordRoute: PortalResetPasswordRoute,
  PortalTradeWorkspaceRoute: PortalTradeWorkspaceRoute,
  SymbolSlugRoute: SymbolSlugRoute,
  ApiPortalAdminStaffRoute: ApiPortalAdminStaffRoute,
  ApiPortalAssetListingsRoute: ApiPortalAssetListingsRoute,
  ApiPortalAuditLogsRoute: ApiPortalAuditLogsRoute,
  ApiPortalAuthDiagnosticsRoute: ApiPortalAuthDiagnosticsRoute,
  ApiPortalClientsAdminRoute: ApiPortalClientsAdminRoute,
  ApiPortalFundingReviewRoute: ApiPortalFundingReviewRoute,
  ApiPortalInvestorOnboardingRoute: ApiPortalInvestorOnboardingRoute,
  ApiPortalInvestorTradingRoute: ApiPortalInvestorTradingRoute,
  ApiPortalMfaRoute: ApiPortalMfaRoute,
  ApiPortalMyWalletsRoute: ApiPortalMyWalletsRoute,
  ApiPortalOnboardClientRoute: ApiPortalOnboardClientRoute,
  ApiPortalProfileRoute: ApiPortalProfileRoute,
  ApiPortalStaffTradeHistoryRoute: ApiPortalStaffTradeHistoryRoute,
  ApiPortalSubPortfolioHoldingsRoute: ApiPortalSubPortfolioHoldingsRoute,
  ApiPortalSubPortfoliosRoute: ApiPortalSubPortfoliosRoute,
  ApiPortalTicketsRoute: ApiPortalTicketsRoute,
  ApiPortalTradeHistoryRoute: ApiPortalTradeHistoryRoute,
  ApiPortalWalletActionsRoute: ApiPortalWalletActionsRoute,
  ApiPublicAdminSignupRoute: ApiPublicAdminSignupRoute,
  ApiPublicAssetListingQuotesRoute: ApiPublicAssetListingQuotesRoute,
  ApiPublicAuthHealthRoute: ApiPublicAuthHealthRoute,
  ApiPublicLiveMarketNewsRoute: ApiPublicLiveMarketNewsRoute,
  ApiPublicLiveMarketQuotesRoute: ApiPublicLiveMarketQuotesRoute,
  ApiPublicPaypalWebhookRoute: ApiPublicPaypalWebhookRoute,
  ApiPublicResolveLoginEmailRoute: ApiPublicResolveLoginEmailRoute,
  ApiPublicSchemaReadinessRoute: ApiPublicSchemaReadinessRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicSymbolDetailRoute: ApiPublicSymbolDetailRoute,
  ApiPublicTickerQuotesRoute: ApiPublicTickerQuotesRoute,
  PortalLoginAdminRoute: PortalLoginAdminRoute,
  PortalLoginInvestorRoute: PortalLoginInvestorRoute,
  PortalSignupInvestorRoute: PortalSignupInvestorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
